version: "3.8"
networks:
  login-net:
    driver: bridge
    name: login-net
  db-postgresql-net:
    name: db-postgresql-net
    driver: bridge

services:
  login-back:
    container_name: "login-back"
    image: sopdockerdesenv01.sop.local:5000/backend/login-back
    networks:
      - login-net
      - db-postgresql-net
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAVEN_PROFILE=${MAVEN_PROFILE}
    ports:
      - "8081:8081"
    restart: unless-stopped
